[package]
name = "multitarget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="multifile"
path="src/bin/singlefile.rs" # Overwrites singlefile.rs
#test=false

[dependencies]
